// copy.js — every UI string lives here (UX-FLOWS §7, verbatim).
NTI.define("core/copy", function () {
  return {
    searchPlaceholder: (n) => `Search ${n} items`,
    hint: "Press / to search. Press ? for shortcuts.",
    nothingMatches: "Nothing matches",
    nothingMatchesBody:
      "Try fewer words or remove a filter. Search covers titles, headings and text inside lessons and PDFs.",
    clearFilters: "Clear filters",
    nothingHere: "Nothing here yet",
    nothingHereBody: "This track has no material yet.",
    backToLibrary: "Back to Library",
    noPdfs: "No PDFs yet",
    noPdfsBody:
      "PDFs show up here as soon as they are added. You can also open one from your computer.",
    openPdfFromComputer: "Open a PDF from your computer",
    howToAdd: "How to add PDFs",
    noPdfsMatch: "No PDFs match",
    noPdfsMatchBody: "Try removing a filter.",
    needsInternet: "Needs internet",
    onlineOnly: "This course is online only. Reconnect to open it.",
    fatal: "The library data didn't load",
    fatalBody:
      "Reload the page. If it keeps happening, the content folder may be incomplete.",
    reload: "Reload",
    refreshThenReload: "Run refresh, then reload.",
    lessonFailed: "This lesson didn't load",
    lessonFailedBody: "The file may be missing from the content folder.",
    tryAgain: "Try again",
    backTo: (t) => `Back to ${t}`,
    pdfMissing: "This PDF isn't in the library folder",
    pdfMissingBody: "It may have been moved or renamed.",
    pdfBlocked: "Open this PDF in your PDF app",
    pdfBlockedBody: "Your browser can't show PDFs inside the page.",
    openPdf: "Open PDF",
    download: "Download",
    pdfPendingTip: "The PDF isn't added yet.",
    comingSoon: "Coming soon",
    comingSoonBody: "This PDF hasn't been added yet.",
    noProgress: "Nothing started. Pick a lesson from the Library or follow the Roadmap.",
    openRoadmap: "Open Roadmap",
    noBookmarks: "No bookmarks yet. Press b on a lesson to save it.",
    noFiles: "No files on this device. Drag a PDF onto the page or open one from your computer.",
    storageBlocked: "This browser can't save your progress. Export it to keep it.",
    backupTitle: "Back up your progress",
    backupBody: "Progress is saved in this browser only.",
    exportBtn: "Export",
    importBtn: "Import",
    imported: "Progress imported",
    importFailed: "That file isn't a progress backup.",
    dropPdf: "Drop a PDF to open it",
    dropStays: "It stays on this device.",
    onlyPdf: "Only PDF files can be added.",
    savedFiles: "Saved to My files",
    storageFull: "Couldn't save this file. Free some space or remove old files.",
    sessionOnly: "Opened for this session only.",
    markedDone: "Marked done",
    bookmarked: "Bookmarked",
    removed: "Removed",
    copied: "Copied",
    undo: "Undo",
    loading: "Loading",
    indexing: "Indexing…",
    originalStyle: "Shown in its original style",
    openNewTab: "Open in new tab",
    libraryInfo: "Nothing you do here leaves this device.",
    paletteFooter: "Search covers this library. Course sites open in a new tab.",
    markDone: "Mark done",
    markDoneContinue: "Mark done and continue",
    bookmark: "Bookmark",
    continueBtn: "Continue",
    start: "Start",
    resume: "Resume",
    open: "Open",
    heroEyebrow: "Engineered for NTI Egypt, offline first",
    heroTitleLead: "Learn DevOps,",
    heroTitleAccent: "one page",
    heroTitleTail: "at a time.",
    heroBody: "Read offline, search every page, and track your progress through cloud infrastructure without high-friction signups.",
    searchCta: "What do you want to learn today?",
    searchTip: "Tip: press Ctrl/Cmd + K to search anywhere.",
    popularLabel: "Popular:",
    popular: ["kubernetes ingress", "docker volumes", "ansible roles"],
    continueEyebrow: "Continue reading",
    statsOffline: "100% offline",
    statsOfflineBody: "Local storage caching, zero network loss.",
    howTitle: "How it works",
    howBody: "No complicated registration. Pure offline-ready knowledge transfer.",
    howSteps: [
      ["Pick a track", "Select from curated topics built around industry demands and NTI tracks."],
      ["Read a PDF or open a course", "Open right in your browser or save it locally. Every paragraph and snippet is indexed."],
      ["Watch your progress grow", "Your browser stores checkpoints safely on your device. Zero cloud sync delays."],
    ],
    footerTag: "Free, offline-first DevOps learning. No tracking, no accounts.",
    heroCtaTracks: "Browse tracks",
    heroCtaRoadmap: "Follow the roadmap",
    tracksTitle: "Tracks",
    tracksBody: "Nine jobs in six stages. Nothing is locked, prerequisites are suggestions.",
    openTrack: "Open track",
    cmdDeckTitle: "Quick command deck",
    cmdDeckBody: "One tap to copy. Full lessons below carry the detail.",
    copyCmd: "Copy",
    studyDeckTitle: "Study deck",
    studyDeckBody: "Flip, recall, master. Open the online course for the full deck.",
    onlineCourse: "Online course",
    journeyEyebrow: "NTI Egypt curriculum flow",
    journeyTitle: "Your learning journey",
    journeyBody: "A suggested path. Learn in any order you like. The order is a recommendation, not a rule.",
    savedLocal: "Progress saved only in this browser.",
    overallProgress: "Overall progress",
    tracksRemaining: (n) => `${n} tracks remaining`,
    mapKey: "Map key",
    statusDone: "Done",
    statusProgress: "In progress",
    statusTodo: "Not started",
    nextUp: "Next up in sequence",
    tracksEyebrow: "Curriculum roadmap",
    allTracksTitle: "All tracks",
    allTracksBody: "Nine topics, one friendly place to learn them.",
    continueOf: (d, t) => `Continue (${d}/${t})`,
    crumbTracks: "Tracks",
    interactiveTrack: "Interactive track",
    requiresInternet: "Requires live internet",
    upNext: "Up next",
    offlineReady: "Offline ready",
    worksOffline: "Works offline",
    readAgain: "Read again",
    startReading: "Start reading",
    continueReading: "Continue reading",
    bundleSize: (mb) => `Bundle size: ${mb} MB`,
    suggestedOrder: "Suggested reading order",
    lostEyebrow: "Route unresolved",
    lostTitle: "Oops, this page wandered off.",
    lostBody: "Even the best setups return a 404 sometimes. Get back on track without losing your place.",
    resumeReading: "Resume reading",
    backHome: "Back to home",
    popularJumps: "Popular jump points:",
    resultsCount: (n) => `${n} results`,
    indexedLocal: "Indexed locally, offline query.",
    localPrivate: "100% local and private",
    meBody: "Your offline learning hub. Everything here stays inside this browser.",
    curriculumOverview: "Curriculum overview",
    tracksStatus: "Tracks status breakdown",
    recentActivity: "Recent activity",
    statusUpcoming: "Upcoming",
    archiveTeaser: "Looking for labs and scripts?",
    archiveTeaserLink: "They are in the Archive.",
    archiveTitle: "Archive",
    aboutTitle: "About and help",
    aboutOpen: "Open source",
    aboutVerified: "Verified curriculum",
    aboutStatic: "Static site: no tracking, works from a file or GitHub Pages.",
    archiveEyebrow: "Auxiliary repository",
    archiveTitle: "Archive: labs, scripts and documents",
    archiveBody: "Supplementary material, reference architectures, and standalone scripts. Kept available offline, separate from the primary tracks.",
    filterPlaceholder: "Filter by title or keyword...",
    allTracksFilter: "All tracks",
    alphaSort: "Alphabetical (A-Z)",
    tabAll: "All",
    tabLabs: "Labs",
    tabScripts: "Scripts",
    tabDocs: "Documents",
    itemsAvailable: (n) => `${n} items available`,
    showMore: (n, s, t) => `Show ${n} more items (${s} of ${t} displayed)`,
    backToTracks: "Back to core tracks",
    archiveCrumb: "Archive",
    backToArchive: "Back to Archive",
    cachedLocal: "Cached locally",
    bundleSizeShort: (mb) => `Bundle size: ${mb} MB`,
    attachedGuide: "Attached lab guide",
    openViewer: "Open in viewer",
    labSteps: "Lab steps",
    setupCheck: (d, t) => `Setup check ${d}/${t}`,
    nextStepHint: "Press Alt + J for next step",
    courseView: "Course view",
    courseEyebrow: "External course",
    sandboxState: "Demo sandbox state",
    sandboxLoaded: "Loaded",
    sandboxOffline: "Offline",
    blockedEmbed: "Blocked embed",
    embedNote: "External course sites may block embedding, so this view keeps the course outside the page. Open it in a new tab anytime.",
    httpsVerified: "HTTPS verified",
    syllabusTitle: "Curriculum syllabus",
    offlineSnapshots: "Cached offline snapshots",
    finishCourse: "I finished this course",
    courseDone: "Course done",
    preIndexed: "All archive scripts and documents are pre-indexed for offline reading.",
    aboutEyebrow: "NTI mentorship, self-paced cloud engineering",
    aboutTitle: "About DevOps By Nabawy",
    aboutBody: "A free, offline-first curriculum designed for NTI students and aspiring DevOps engineers.",
    motivationTitle: "Built for real students living in the real world.",
    motivationBody: "Zero registration forms, instant local caching in your browser, and zero behavioral telemetry.",
    pillarOffline: "100% offline-first",
    pillarOfflineBody: "PDFs and guides cache into the browser on first load. Study uninterrupted.",
    pillarUntethered: "Zero cloud tether",
    pillarUntetheredBody: "No accounts, no passwords, no analytics, no ads. Progress lives on your device only.",
    pillarNti: "Tailored for NTI",
    pillarNtiBody: "Mapped to the NTI syllabus, hiring standards, and hands-on troubleshooting scenarios.",
    versionLabel: (v) => `Version ${v}, offline ready`,
  };
});
