// copy.js — every UI string lives here (UX-FLOWS §7, verbatim).
NTI.define("core/copy", function () {
  return {
    searchPlaceholder: (n) => `Search ${n} items`,
    hint: "Press / to search. Press ? for shortcuts.",
    nothingMatches: "Nothing matches",
    nothingMatchesBody:
      "Try fewer words or remove a filter. Search covers titles, headings and text inside lessons and PDFs.",
    clearFilters: "Clear filters",
    nothingHere: "Nothing here yet",
    nothingHereBody: "This track has no material yet.",
    backToLibrary: "Back to Library",
    noPdfs: "No PDFs yet",
    noPdfsBody:
      "PDFs show up here as soon as they are added. You can also open one from your computer.",
    openPdfFromComputer: "Open a PDF from your computer",
    howToAdd: "How to add PDFs",
    noPdfsMatch: "No PDFs match",
    noPdfsMatchBody: "Try removing a filter.",
    needsInternet: "Needs internet",
    onlineOnly: "This course is online only. Reconnect to open it.",
    fatal: "The library data didn't load",
    fatalBody:
      "Reload the page. If it keeps happening, the content folder may be incomplete.",
    reload: "Reload",
    refreshThenReload: "Run refresh, then reload.",
    lessonFailed: "This lesson didn't load",
    lessonFailedBody: "The file may be missing from the content folder.",
    tryAgain: "Try again",
    backTo: (t) => `Back to ${t}`,
    pdfMissing: "This PDF isn't in the library folder",
    pdfMissingBody: "It may have been moved or renamed.",
    pdfBlocked: "Open this PDF in your PDF app",
    pdfBlockedBody: "Your browser can't show PDFs inside the page.",
    openPdf: "Open PDF",
    download: "Download",
    pdfPendingTip: "The PDF isn't added yet.",
    comingSoon: "Coming soon",
    comingSoonBody: "This PDF hasn't been added yet.",
    noProgress: "Nothing started. Pick a lesson from the Library or follow the Roadmap.",
    openRoadmap: "Open Roadmap",
    noBookmarks: "No bookmarks yet. Press b on a lesson to save it.",
    noFiles: "No files on this device. Drag a PDF onto the page or open one from your computer.",
    storageBlocked: "This browser can't save your progress. Export it to keep it.",
    backupTitle: "Back up your progress",
    backupBody: "Progress is saved in this browser only.",
    exportBtn: "Export",
    importBtn: "Import",
    imported: "Progress imported",
    importFailed: "That file isn't a progress backup.",
    dropPdf: "Drop a PDF to open it",
    dropStays: "It stays on this device.",
    onlyPdf: "Only PDF files can be added.",
    savedFiles: "Saved to My files",
    storageFull: "Couldn't save this file. Free some space or remove old files.",
    sessionOnly: "Opened for this session only.",
    markedDone: "Marked done",
    bookmarked: "Bookmarked",
    removed: "Removed",
    copied: "Copied",
    undo: "Undo",
    loading: "Loading",
    indexing: "Indexing…",
    originalStyle: "Shown in its original style",
    openNewTab: "Open in new tab",
    libraryInfo: "Nothing you do here leaves this device.",
    paletteFooter: "Search covers this library. Course sites open in a new tab.",
    markDone: "Mark done",
    markDoneContinue: "Mark done and continue",
    bookmark: "Bookmark",
    continueBtn: "Continue",
    start: "Start",
    resume: "Resume",
    open: "Open",
    heroTitle: "DevOps By Nabawy",
    heroBody: "One library for the full pipeline, from Linux to delivery. Pick a track, follow the roadmap, resume in one tap.",
    heroCtaTracks: "Browse tracks",
    heroCtaRoadmap: "Follow the roadmap",
    tracksTitle: "Tracks",
    tracksBody: "Nine jobs in six stages. Nothing is locked, prerequisites are suggestions.",
    openTrack: "Open track",
    cmdDeckTitle: "Quick command deck",
    cmdDeckBody: "One tap to copy. Full lessons below carry the detail.",
    copyCmd: "Copy",
    studyDeckTitle: "Study deck",
    studyDeckBody: "Flip, recall, master. Open the online course for the full deck.",
    onlineCourse: "Online course",
  };
});
