/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpenRouteImport } from './routes/open'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as TracksIndexRouteImport } from './routes/tracks.index'
import { Route as TracksSlugRouteImport } from './routes/tracks.$slug'
import { Route as TracksCicdRouteImport } from './routes/tracks.cicd'
import { Route as TracksLinuxRouteImport } from './routes/tracks.linux'
import { Route as TracksTerraformRouteImport } from './routes/tracks.terraform'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenRoute = OpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksIndexRoute = TracksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TracksRoute,
} as any)
const TracksSlugRoute = TracksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TracksRoute,
} as any)
const TracksCicdRoute = TracksCicdRouteImport.update({
  id: '/cicd',
  path: '/cicd',
  getParentRoute: () => TracksRoute,
} as any)
const TracksLinuxRoute = TracksLinuxRouteImport.update({
  id: '/linux',
  path: '/linux',
  getParentRoute: () => TracksRoute,
} as any)
const TracksTerraformRoute = TracksTerraformRouteImport.update({
  id: '/terraform',
  path: '/terraform',
  getParentRoute: () => TracksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/open': typeof OpenRoute
  '/roadmap': typeof RoadmapRoute
  '/tracks': typeof TracksRouteWithChildren
  '/books/$bookId': typeof BooksBookIdRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/tracks/cicd': typeof TracksCicdRoute
  '/tracks/linux': typeof TracksLinuxRoute
  '/tracks/terraform': typeof TracksTerraformRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/open': typeof OpenRoute
  '/roadmap': typeof RoadmapRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/tracks/cicd': typeof TracksCicdRoute
  '/tracks/linux': typeof TracksLinuxRoute
  '/tracks/terraform': typeof TracksTerraformRoute
  '/tracks': typeof TracksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/open': typeof OpenRoute
  '/roadmap': typeof RoadmapRoute
  '/tracks': typeof TracksRouteWithChildren
  '/books/$bookId': typeof BooksBookIdRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/tracks/cicd': typeof TracksCicdRoute
  '/tracks/linux': typeof TracksLinuxRoute
  '/tracks/terraform': typeof TracksTerraformRoute
  '/tracks/': typeof TracksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/open'
    | '/roadmap'
    | '/tracks'
    | '/books/$bookId'
    | '/tracks/$slug'
    | '/tracks/cicd'
    | '/tracks/linux'
    | '/tracks/terraform'
    | '/tracks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/open'
    | '/roadmap'
    | '/books/$bookId'
    | '/tracks/$slug'
    | '/tracks/cicd'
    | '/tracks/linux'
    | '/tracks/terraform'
    | '/tracks'
  id:
    | '__root__'
    | '/'
    | '/open'
    | '/roadmap'
    | '/tracks'
    | '/books/$bookId'
    | '/tracks/$slug'
    | '/tracks/cicd'
    | '/tracks/linux'
    | '/tracks/terraform'
    | '/tracks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpenRoute: typeof OpenRoute
  RoadmapRoute: typeof RoadmapRoute
  TracksRoute: typeof TracksRouteWithChildren
  BooksBookIdRoute: typeof BooksBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open': {
      id: '/open'
      path: '/open'
      fullPath: '/open'
      preLoaderRoute: typeof OpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/': {
      id: '/tracks/'
      path: '/'
      fullPath: '/tracks/'
      preLoaderRoute: typeof TracksIndexRouteImport
      parentRoute: typeof TracksRoute
    }
    '/tracks/$slug': {
      id: '/tracks/$slug'
      path: '/$slug'
      fullPath: '/tracks/$slug'
      preLoaderRoute: typeof TracksSlugRouteImport
      parentRoute: typeof TracksRoute
    }
    '/tracks/cicd': {
      id: '/tracks/cicd'
      path: '/cicd'
      fullPath: '/tracks/cicd'
      preLoaderRoute: typeof TracksCicdRouteImport
      parentRoute: typeof TracksRoute
    }
    '/tracks/linux': {
      id: '/tracks/linux'
      path: '/linux'
      fullPath: '/tracks/linux'
      preLoaderRoute: typeof TracksLinuxRouteImport
      parentRoute: typeof TracksRoute
    }
    '/tracks/terraform': {
      id: '/tracks/terraform'
      path: '/terraform'
      fullPath: '/tracks/terraform'
      preLoaderRoute: typeof TracksTerraformRouteImport
      parentRoute: typeof TracksRoute
    }
  }
}

interface TracksRouteChildren {
  TracksSlugRoute: typeof TracksSlugRoute
  TracksCicdRoute: typeof TracksCicdRoute
  TracksLinuxRoute: typeof TracksLinuxRoute
  TracksTerraformRoute: typeof TracksTerraformRoute
  TracksIndexRoute: typeof TracksIndexRoute
}

const TracksRouteChildren: TracksRouteChildren = {
  TracksSlugRoute: TracksSlugRoute,
  TracksCicdRoute: TracksCicdRoute,
  TracksLinuxRoute: TracksLinuxRoute,
  TracksTerraformRoute: TracksTerraformRoute,
  TracksIndexRoute: TracksIndexRoute,
}

const TracksRouteWithChildren =
  TracksRoute._addFileChildren(TracksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpenRoute: OpenRoute,
  RoadmapRoute: RoadmapRoute,
  TracksRoute: TracksRouteWithChildren,
  BooksBookIdRoute: BooksBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
